version: '3'

services:
  web:
    image: node:16-alpine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
